### ISSUE TITLE
Missing double spaces in market hashes.

### ISSUE THREAD

**Issue by Zeprix** [ModestSerhat/buff163-ids#5]
Some items in the buffids.json have a single space instead of a double one that is on steam and buff itself. This issue makes some items be unfindable by a dict key.

**Comment by ModestSerhat** [comment]
You can use the Steam Market name-Buff Goods ID pair JSON below to search items with double spaces on their Steam Market names, the item names on buffids.json won't be changed since Buff163 uses single spaces for these items.
`
{
"Sticker | AdreN  | MLG Columbus 2016": 39841,
"Sticker | AdreN (Foil)  | MLG Columbus 2016": 39842,
"Sticker | Ninjas in Pyjamas  | Katowice 2015": 40612,
"Sticker | PENTA Sports  | Katowice 2015": 40648,
"Sticker | Vox Eminor  | Katowice 2015": 41046,
"Sticker | niko (Foil)  | London 2018": 760994,
"Sticker | niko  | London 2018": 760995,
"Sticker | niko (Gold)  | London 2018": 761213,
"Michael Syfers  | FBI Sniper": 774827,
"Ground Rebel  | Elite Crew": 774881
}
`

**Comment by ModestSerhat** [comment]
You can use the Steam Market name-Buff Goods ID pair JSON below to search items with double spaces on their Steam Market names, the item names on buffids.json won't be changed since Buff163 uses single spaces for these items.
```
{
    "Sticker | AdreN  | MLG Columbus 2016": 39841,
    "Sticker | AdreN (Foil)  | MLG Columbus 2016": 39842,
    "Sticker | Ninjas in Pyjamas  | Katowice 2015": 40612,
    "Sticker | PENTA Sports  | Katowice 2015": 40648,
    "Sticker | Vox Eminor  | Katowice 2015": 41046,
    "Sticker | niko (Foil)  | London 2018": 760994,
    "Sticker | niko  | London 2018": 760995,
    "Sticker | niko (Gold)  | London 2018": 761213,
    "Michael Syfers  | FBI Sniper": 774827,
    "Ground Rebel  | Elite Crew": 774881
}
```

**Comment by Zeprix** [comment]
On the app atleast buff does use double spaces. 
I added a image with a single space and a double one.
![IMG_3366](https://github.com/ModestSerhat/buff163-ids/assets/63049096/a07ca8ca-012a-4fe1-b493-c949f4f557f3)

**Comment by ModestSerhat** [comment]
I didn't know that the Buff app still had the double spaces on some items as they were fixed on the website, I will add Name and Goods/Sticker ID pair JSON files of buffids_ds.json and stickerids_ds.json for double spaced items soon, thank you!

**Comment by ModestSerhat** [comment]
The sticker names for stickerids.json don't have the same double space problem even in the Buff app so a stickerids_ds.json, buffids_ds.json for double spaced item names is added now!
